version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file lambda_code/samTemplate.json --s3-bucket testbucketforapi --output-template-file outputSamTemplate.json
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
